# 📊 Notebook 03: Modeling Time Series

Notebook ini menjalankan proses pemodelan **time series forecasting** menggunakan PyCaret.

**Alur Kerja:**
1. Import library & definisi konstanta
2. Definisi kelas `EksperimenSaham` (OOP)
3. Eksekusi pipeline: Muat Data → Setup → Cari Model Terbaik → Visualisasi → Simpan

## Cell 1: Import Library

In [ ]:
import os
import json
import warnings
import pandas as pd
from pathlib import Path
from pycaret.time_series import (
    setup,
    compare_models,
    pull,
    save_model,
    plot_model,
)
from IPython.display import display

warnings.filterwarnings('ignore')

## Cell 2: Konstanta & Path

In [4]:
# Definisi path menggunakan pathlib
BASE_DIR = Path('..')
DATA_PROCESSED_DIR = BASE_DIR / 'Data' / 'Processed'
JSON_TICKER_PATH   = BASE_DIR / 'Data' / 'Raw' / 'tickers_us.json'

# Arahkan output langsung ke folder Monthly
MODEL_MONTHLY_DIR  = BASE_DIR / 'Models' / 'Monthly'
os.makedirs(MODEL_MONTHLY_DIR, exist_ok=True)

# Konstanta strategi
UKURAN_TRAINING = 180     # 15 tahun (180 bulan)
HORIZON_PREDIKSI = 12    # Prediksi 1 tahun ke depan
JUMLAH_FOLD = 5

## Cell 3: Ambil Daftar Saham dari JSON

In [5]:
def ambil_daftar_saham(json_path: Path) -> list:
    """Membaca file JSON dan mengambil ticker yang statusnya available."""
    with open(json_path, 'r') as f:
        data = json.load(f)
    return [t['ticker'] for t in data['tickers'] if t['available']]

daftar_saham = ambil_daftar_saham(JSON_TICKER_PATH)

## Cell 4: Definisi Kelas `EksperimenSaham`

In [7]:
class EksperimenSaham:
    def __init__(self, ticker: str):
        self.ticker = ticker
        self.df = None
        self.model_terbaik = None

    def muat_data_bulanan(self, folder_path: Path):
        """Mengambil data khusus bulanan."""
        file_path = folder_path / f'{self.ticker}_monthly.parquet'
        self.df = pd.read_parquet(file_path)
        if 'Date' in self.df.columns:
            self.df.set_index('Date', inplace=True)
        if hasattr(self.df.index, 'tz'):
            self.df.index = self.df.index.tz_localize(None)
        self.df = self.df.asfreq('M')
        self.df.ffill(inplace=True)
        return self

    def jalankan_setup(self, horizon: int, ukuran_training: int):
        """Setup PyCaret dengan Log Transformation."""
        jumlah_potong = ukuran_training + horizon
        data_final = self.df.tail(jumlah_potong) if len(self.df) > jumlah_potong else self.df
        
        setup(
            data=data_final[['Close']],
            fh=horizon,
            fold=JUMLAH_FOLD,
            fold_strategy='sliding',
            seasonal_period=12,
            transform_target='log', # <--- Log Transform Aktif
            session_id=123,
            verbose=False,
        )
        return self

    def cari_model_terbaik(self):
        self.model_terbaik = compare_models(sort='MAE')
        return self

    def simpan_ke_monthly(self, output_dir: Path):
        """Simpan model ke folder Models/Monthly."""
        nama_file = output_dir / f'{self.ticker}_model_bulanan'
        save_model(self.model_terbaik, str(nama_file))
        return self

## Cell 5: Eksekusi Pipeline — AAPL

Menjalankan seluruh pipeline untuk saham **AAPL** (Apple Inc).

In [8]:
eksperimen_aapl = EksperimenSaham('AAPL')
(
    eksperimen_aapl
    .muat_data_bulanan(DATA_PROCESSED_DIR)
    .jalankan_setup(horizon=HORIZON_PREDIKSI, ukuran_training=UKURAN_TRAINING)
    .cari_model_terbaik()
    .simpan_ke_monthly(MODEL_MONTHLY_DIR)
)

print(f'\n>>> [SEL 5] Hasil Eksperimen AAPL (LOG):')
display(pull())
plot_model(eksperimen_aapl.model_terbaik, plot='forecast')

Transformation Pipeline and Model Successfully Saved

>>> [SEL 5] Hasil Eksperimen AAPL (LOG):

,Model,MASE,RMSSE,MAE,RMSE,MAPE,SMAPE,R2,TT (Sec)
theta,Theta Forecaster,1.7806,1.4043,20.8845,23.5911,0.1388,0.1506,-3.2011,0.014
auto_arima,Auto ARIMA,1.6911,1.3293,21.3945,23.8958,0.1383,0.1429,-3.5988,0.124
arima,ARIMA,1.5817,1.3062,21.6718,25.7033,0.1406,0.1351,-3.6947,0.026
exp_smooth,Exponential Smoothing,1.7257,1.3739,21.9837,24.929,0.1446,0.1458,-4.3222,0.018
ets,ETS,1.7257,1.3739,21.9841,24.9292,0.1446,0.1458,-4.3223,0.022
omp_cds_dt,Orthogonal Matching Pursuit w/ Cond. Deseasona...,2.1497,1.687,25.5556,29.1885,0.1709,0.1846,-5.5981,0.038
naive,Naive Forecaster,2.1424,1.633,25.6639,27.779,0.1635,0.1862,-4.92,0.652
stlf,STLF,2.1282,1.6494,28.6159,31.8683,0.1878,0.1821,-6.2887,0.014
rf_cds_dt,Random Forest w/ Cond. Deseasonalize & Detrending,2.3567,1.8754,28.6374,32.5901,0.1944,0.2021,-6.9262,0.082
ada_cds_dt,AdaBoost w/ Cond. Deseasonalize & Detrending,2.3844,1.8827,29.0751,32.5864,0.1961,0.2052,-7.2337,0.044
lightgbm_cds_dt,Light Gradient Boosting w/ Cond. Deseasonalize...,2.4561,1.9552,29.9041,34.0679,0.2011,0.213,-7.3514,0.080
et_cds_dt,Extra Trees w/ Cond. Deseasonalize & Detrending,2.6314,2.0659,30.2773,34.7367,0.2017,0.2412,-8.8721,0.078
gbr_cds_dt,Gradient Boosting w/ Cond. Deseasonalize & Det...,2.6873,2.0953,30.8536,35.1856,0.2057,0.2491,-9.4834,0.044
en_cds_dt,Elastic Net w/ Cond. Deseasonalize & Detrending,2.7873,2.0856,33.0258,35.9616,0.2193,0.2514,-9.4924,0.096
lasso_cds_dt,Lasso w/ Cond. Deseasonalize & Detrending,2.7873,2.0856,33.0258,35.9616,0.2193,0.2514,-9.4924,0.038
llar_cds_dt,Lasso Least Angular Regressor w/ Cond. Deseaso...,2.7873,2.0856,33.0258,35.9616,0.2193,0.2514,-9.4924,0.050
br_cds_dt,Bayesian Ridge w/ Cond. Deseasonalize & Detren...,2.7653,2.1266,33.0628,37.0529,0.2191,0.2489,-10.0955,0.038
lr_cds_dt,Linear w/ Cond. Deseasonalize & Detrending,2.7642,2.1288,33.0778,37.143,0.2189,0.2487,-10.1805,0.096
ridge_cds_dt,Ridge w/ Cond. Deseasonalize & Detrending,2.798,2.1398,33.2774,37.0832,0.222,0.2527,-9.8357,0.068
polytrend,Polynomial Trend Forecaster,2.847,2.1584,34.1751,37.7928,0.2248,0.2551,-10.2909,0.012
huber_cds_dt,Huber w/ Cond. Deseasonalize & Detrending,2.8097,2.1711,34.1914,38.5735,0.2248,0.2528,-11.1454,0.044
snaive,Seasonal Naive Forecaster,2.9934,2.2593,36.5623,39.3722,0.2357,0.2798,-10.8718,0.314
knn_cds_dt,K Neighbors w/ Cond. Deseasonalize & Detrending,3.3219,2.4763,40.4719,43.8294,0.2726,0.3084,-12.8976,0.072
dt_cds_dt,Decision Tree w/ Cond. Deseasonalize & Detrending,3.4066,2.6364,43.6468,48.2824,0.2727,0.3072,-21.2551,0.038
croston,Croston,3.5791,2.6285,44.3509,46.2289,0.2801,0.3446,-15.1348,0.012
grand_means,Grand Means Forecaster,8.7822,6.2146,124.5147,125.1462,0.7571,1.2213,-111.6766,0.292

## Cell 6: Visualisasi & Simpan Model — AAPL

In [9]:
# Visualisasi hasil prediksi
eksperimen_aapl.tampilkan_visualisasi()

# Simpan model terbaik ke folder Models/
eksperimen_aapl.simpan_model(MODEL_OUTPUT_DIR)

AttributeError: 'EksperimenSaham' object has no attribute 'tampilkan_visualisasi'

In [9]:
## Cell 7: Loop Pemodelan Massal (Bulk Modeling)
# Menjalankan pipeline untuk semua ticker yang tersedia secara otomatis.

print(f">>> Memulai pemodelan massal untuk {len(daftar_saham)} saham...")

# Wadah untuk menyimpan ringkasan hasil
ringkasan_semua_model = []

for ticker in daftar_saham:
    try:
        # 1. Inisialisasi
        eksperimen = EksperimenSaham(ticker)
        
        # 2. Eksekusi Pipeline (Muat -> Setup -> Cari Model -> Simpan)
        (
            eksperimen
            .muat_data(DATA_PROCESSED_DIR)
            .jalankan_setup(horizon=HORIZON_PREDIKSI, ukuran_training=UKURAN_TRAINING)
            .cari_model_terbaik()
        )
        
        # 3. Simpan Model ke Folder Models/
        eksperimen.simpan_model(MODEL_OUTPUT_DIR)
        
        # 4. Catat hasil terbaik untuk ringkasan akhir
        best_metrics = pull().iloc[0] # Ambil baris pertama (juara)
        ringkasan_semua_model.append({
            'Ticker': ticker,
            'Model Terbaik': best_metrics['Model'],
            'MAE': best_metrics['MAE'],
            'RMSE': best_metrics['RMSE'],
            'R2': best_metrics['R2']
        })
        
        print(f">>> [SUKSES] {ticker} selesai diproses.\n")
        
    except Exception as e:
        print(f">>> [GAGAL] Terjadi error pada ticker {ticker}: {str(e)}\n")

# Tampilkan ringkasan akhir semua saham
df_ringkasan = pd.DataFrame(ringkasan_semua_model)
print("="*50)
print("RINGKASAN PEMODELAN SELURUH SAHAM")
print("="*50)
display(df_ringkasan)

>>> Memulai pemodelan massal untuk 30 saham...
>>> [AAPL] Data dimuat: 253 baris
>>> [AAPL] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [AAPL] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [AAPL] Model tersimpan di: ../Models/AAPL_model_terbaik
>>> [SUKSES] AAPL selesai diproses.

>>> [MSFT] Data dimuat: 253 baris
>>> [MSFT] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [MSFT] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [MSFT] Model tersimpan di: ../Models/MSFT_model_terbaik
>>> [SUKSES] MSFT selesai diproses.

>>> [GOOGL] Data dimuat: 253 baris
>>> [GOOGL] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [GOOGL] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [GOOGL] Model tersimpan di: ../Models/GOOGL_model_terbaik
>>> [SUKSES] GOOGL selesai diproses.

>>> [AMZN] Data dimuat: 253 baris
>>> [AMZN] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [AMZN] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [AMZN] Model tersimpan di: ../Models/AMZN_model_terbaik
>>> [SUKSES] AMZN selesai diproses.

>>> [NVDA] Data dimuat: 253 baris
>>> [NVDA] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [NVDA] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [NVDA] Model tersimpan di: ../Models/NVDA_model_terbaik
>>> [SUKSES] NVDA selesai diproses.

>>> [META] Data dimuat: 169 baris
>>> [META] Memulai setup PyCaret...
    Setup berhasil! (fh=12, fold=5)
>>> [META] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [META] Model tersimpan di: ../Models/META_model_terbaik
>>> [SUKSES] META selesai diproses.

>>> [TSLA] Data dimuat: 192 baris
>>> [TSLA] Memulai setup PyCaret...
    Setup berhasil! (fh=12, fold=5)
>>> [TSLA] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [TSLA] Model tersimpan di: ../Models/TSLA_model_terbaik
>>> [SUKSES] TSLA selesai diproses.

>>> [AVGO] Data dimuat: 202 baris
>>> [AVGO] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [AVGO] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [AVGO] Model tersimpan di: ../Models/AVGO_model_terbaik
>>> [SUKSES] AVGO selesai diproses.

>>> [AMD] Data dimuat: 253 baris
>>> [AMD] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [AMD] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [AMD] Model tersimpan di: ../Models/AMD_model_terbaik
>>> [SUKSES] AMD selesai diproses.

>>> [ORCL] Data dimuat: 253 baris
>>> [ORCL] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [ORCL] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [ORCL] Model tersimpan di: ../Models/ORCL_model_terbaik
>>> [SUKSES] ORCL selesai diproses.

>>> [BRK-B] Data dimuat: 253 baris
>>> [BRK-B] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [BRK-B] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [BRK-B] Model tersimpan di: ../Models/BRK-B_model_terbaik
>>> [SUKSES] BRK-B selesai diproses.

>>> [JPM] Data dimuat: 253 baris
>>> [JPM] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [JPM] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [JPM] Model tersimpan di: ../Models/JPM_model_terbaik
>>> [SUKSES] JPM selesai diproses.

>>> [V] Data dimuat: 219 baris
>>> [V] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [V] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [V] Model tersimpan di: ../Models/V_model_terbaik
>>> [SUKSES] V selesai diproses.

>>> [MA] Data dimuat: 241 baris
>>> [MA] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [MA] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [MA] Model tersimpan di: ../Models/MA_model_terbaik
>>> [SUKSES] MA selesai diproses.

>>> [BAC] Data dimuat: 253 baris
>>> [BAC] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [BAC] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [BAC] Model tersimpan di: ../Models/BAC_model_terbaik
>>> [SUKSES] BAC selesai diproses.

>>> [LLY] Data dimuat: 253 baris
>>> [LLY] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [LLY] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [LLY] Model tersimpan di: ../Models/LLY_model_terbaik
>>> [SUKSES] LLY selesai diproses.

>>> [UNH] Data dimuat: 253 baris
>>> [UNH] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [UNH] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [UNH] Model tersimpan di: ../Models/UNH_model_terbaik
>>> [SUKSES] UNH selesai diproses.

>>> [JNJ] Data dimuat: 253 baris
>>> [JNJ] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [JNJ] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [JNJ] Model tersimpan di: ../Models/JNJ_model_terbaik
>>> [SUKSES] JNJ selesai diproses.

>>> [MRK] Data dimuat: 253 baris
>>> [MRK] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [MRK] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [MRK] Model tersimpan di: ../Models/MRK_model_terbaik
>>> [SUKSES] MRK selesai diproses.

>>> [ABBV] Data dimuat: 161 baris
>>> [ABBV] Memulai setup PyCaret...
    Setup berhasil! (fh=12, fold=5)
>>> [ABBV] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [ABBV] Model tersimpan di: ../Models/ABBV_model_terbaik
>>> [SUKSES] ABBV selesai diproses.

>>> [WMT] Data dimuat: 253 baris
>>> [WMT] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [WMT] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [WMT] Model tersimpan di: ../Models/WMT_model_terbaik
>>> [SUKSES] WMT selesai diproses.

>>> [PG] Data dimuat: 253 baris
>>> [PG] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [PG] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [PG] Model tersimpan di: ../Models/PG_model_terbaik
>>> [SUKSES] PG selesai diproses.

>>> [COST] Data dimuat: 253 baris
>>> [COST] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [COST] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [COST] Model tersimpan di: ../Models/COST_model_terbaik
>>> [SUKSES] COST selesai diproses.

>>> [HD] Data dimuat: 253 baris
>>> [HD] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [HD] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [HD] Model tersimpan di: ../Models/HD_model_terbaik
>>> [SUKSES] HD selesai diproses.

>>> [KO] Data dimuat: 253 baris
>>> [KO] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [KO] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [KO] Model tersimpan di: ../Models/KO_model_terbaik
>>> [SUKSES] KO selesai diproses.

>>> [PEP] Data dimuat: 253 baris
>>> [PEP] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [PEP] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [PEP] Model tersimpan di: ../Models/PEP_model_terbaik
>>> [SUKSES] PEP selesai diproses.

>>> [CVX] Data dimuat: 253 baris
>>> [CVX] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [CVX] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [CVX] Model tersimpan di: ../Models/CVX_model_terbaik
>>> [SUKSES] CVX selesai diproses.

>>> [XOM] Data dimuat: 253 baris
>>> [XOM] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [XOM] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [XOM] Model tersimpan di: ../Models/XOM_model_terbaik
>>> [SUKSES] XOM selesai diproses.

>>> [CRM] Data dimuat: 253 baris
>>> [CRM] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [CRM] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [CRM] Model tersimpan di: ../Models/CRM_model_terbaik
>>> [SUKSES] CRM selesai diproses.

>>> [NFLX] Data dimuat: 253 baris
>>> [NFLX] Memulai setup PyCaret...
    Data dipotong menjadi 192 baris terakhir
    Setup berhasil! (fh=12, fold=5)
>>> [NFLX] Sedang membandingkan algoritma...

Transformation Pipeline and Model Successfully Saved
>>> [NFLX] Model tersimpan di: ../Models/NFLX_model_terbaik
>>> [SUKSES] NFLX selesai diproses.

==================================================
RINGKASAN PEMODELAN SELURUH SAHAM
==================================================

,Ticker,Model Terbaik,MAE,RMSE,R2
0,AAPL,ETS,21.2915,24.0332,-3.4215
1,MSFT,Auto ARIMA,24.5648,29.6979,-0.5229
2,GOOGL,Huber w/ Cond. Deseasonalize & Detrending,14.1511,17.7863,-1.4358
3,AMZN,Huber w/ Cond. Deseasonalize & Detrending,19.4222,21.5106,-2.8492
4,NVDA,Theta Forecaster,10.7715,13.6142,-2.2951
5,META,Exponential Smoothing,71.5023,88.1713,-1.6202
6,TSLA,Orthogonal Matching Pursuit w/ Cond. Deseasona...,72.6846,85.3131,-1.7613
7,AVGO,Auto ARIMA,16.0093,19.4717,-1.1968
8,AMD,Decision Tree w/ Cond. Deseasonalize & Detrending,25.6188,29.0936,-2.2785
9,ORCL,Auto ARIMA,13.8870,15.8409,-1.6278
10,BRK-B,Theta Forecaster,35.0788,41.0636,-1.1993
11,JPM,Decision Tree w/ Cond. Deseasonalize & Detrending,19.3122,23.4275,-0.8306
12,V,Orthogonal Matching Pursuit w/ Cond. Deseasona...,18.5467,22.9721,-0.3132
13,MA,Orthogonal Matching Pursuit w/ Cond. Deseasona...,34.1229,40.4751,-0.7790
14,BAC,Huber w/ Cond. Deseasonalize & Detrending,2.8764,3.5675,-0.0045
15,LLY,Theta Forecaster,71.7485,85.0637,-1.7162
16,UNH,Auto ARIMA,35.4641,46.1071,-1.2815
17,JNJ,Auto ARIMA,7.8559,9.4616,-0.9553
18,MRK,Huber w/ Cond. Deseasonalize & Detrending,9.9397,12.4305,-1.2011
19,ABBV,ETS,12.5099,14.8336,-0.7504
20,WMT,Exponential Smoothing,6.0172,7.1532,-1.1034
21,PG,Random Forest w/ Cond. Deseasonalize & Detrending,7.8485,9.3508,-1.2947
22,COST,ETS,58.2385,72.4220,-1.3745
23,HD,Exponential Smoothing,26.1399,32.9946,-0.9575
24,KO,Auto ARIMA,3.0944,3.7954,-0.5074
25,PEP,STLF,10.5860,12.6402,-1.9816
26,CVX,AdaBoost w/ Cond. Deseasonalize & Detrending,10.9571,14.0347,-0.4532
27,XOM,ETS,7.9959,10.6403,-1.3344
28,CRM,Decision Tree w/ Cond. Deseasonalize & Detrending,32.5615,39.3280,-1.1339
29,NFLX,Huber w/ Cond. Deseasonalize & Detrending,11.1907,13.4294,-2.8757